#ifndef GIGA_CONFIG_H
#define GIGA_CONFIG_H

#define CYBERDECK_WIFI_SSID "YOUR_WIFI_SSID"
#define CYBERDECK_WIFI_PASS "YOUR_WIFI_PASSWORD"
#define CYBERDECK_UNOQ_HOST "unoq.local"
#define CYBERDECK_UNOQ_PORT 8080

#endif
